apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: ghost
  name: ghost
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghost
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

