apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: ghost
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ghost.svc.cluster.local
    path: "/exports/ghost"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ghost
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
