apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ajotaops/nginx-with-content:v3
        ports:
        - containerPort: 80
---

apiVersion: v1  
kind: Service 
metadata:
  name: nginx-svc 
spec:
  type: NodePort 
  selector:
    app: nginx 
  ports:
    - port: 80 
      targetPort: 80 
      nodePort: 30002
