apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: mysql-pv
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: ghost-pv
  resources:
    requests:
      storage: 5Gi
